import React from 'react';
import { Search, Map, Layout, Zap, Pointer, Target, Layers, Component, Maximize, Database, Server, Cog, Workflow, BarChart2, MessageSquare, Megaphone, ArrowUpRight, MousePointerClick, ShieldCheck, Mail, LineChart, Cpu, Cloud, Building2, TerminalSquare, LayoutDashboard, LockKeyhole, Globe, Store, ShoppingCart, HeartPulse, Navigation, GraduationCap, Shirt, Dumbbell, Scale, Bitcoin, Landmark, Paintbrush, Building, CheckCircle2 } from 'lucide-react';
import { SocialMediaVisual } from '../../../components/services/subservices/visuals/VisualsSoftware_Marketing';
import { ModernServiceLayout } from '../../../components/services/subservices/ModernServiceLayout';

const SocialMedia = () => {
    const seoData = {
        title: "Cultivating Dedicated Brand Cults | The Digital Connect",
        description: "Organic social trajectory strategy explicitly engineering massive community engagement transforming standard followers directly into radical brand evangelists."
    };

    const theme = { "accent": "text-brand-cyan", "bg": "bg-brand-cyan/20", "softBg": "bg-brand-bg-light" };

    const hero = {
        parentTitle: "social media marketing",
        parentRoute: "/services/digital-marketing/social-media",
        eyebrow: "The Best Solution For Your Business",
        title: "Top Social Media Consultancy",
        description: "",
        visual: SocialMediaVisual,
        ctaText: "GET FREE QUOTE NOW"
    };

    const intro = {
        eyebrow: "",
        title: "Trusted Social Media Management Company",
        paragraphs: [
            "Our team at 21Twelve Interactive is one of the best in the field regarding social media marketing services. You may use our social media advertising services to boost your brand’s social media presence or to generate targeted leads. We can help you achieve your objectives within a limited time. Advertising on social media is essential to every company’s social media strategy, regardless of industry. Using social advertising, companies may use various techniques to reach the appropriate audience at the right moment as algorithms evolve.",
            "Promoting your business on various social media platforms has pros and disadvantages. We are a professional social media management company committed to delivering high-end marketing services. We’ll create a social media marketing strategy that will increase both the number of followers and the number of leads you generate. Each week, we’ll post a new, custom-written or graphics-based social media post to assist your company in growing its online presence and outpacing the competition. As a social media agency, we have a proven track record of success. However, despite its increasing popularity as a marketing tactic, we remain mindful of the bigger picture."
        ]
    };

    const process = {
        eyebrow: "Enhance Your Project with Risk Free Development Process",
        title: "Process We Follow",
        description: "The most current social media marketing is generated by using a proven method.",
        steps: [
            { title: "Assessing Your Existing Social Media Presence", desc: "We will first observe your surroundings and social media presence before making plans for the future." },
            { title: "Determining the Ideal Customer for You", desc: "We will research extensively to determine the ideal customers that suit your needs." },
            { title: "Selecting a Channel", desc: "For your company, we focus on the social media outlets that will have the most effect." },
            { title: "Social Strategy & Posting", desc: "We will create and distribute high-quality content with the right strategy, monitoring, and execution." },
            { title: "Promoting Your Business Through Social Media", desc: "We help you promote your business socially with a mixture of organic and paid ads strategies." },
            { title: "Tracking and Analyzing Results", desc: "After all the efforts, we will measure everything, which will help us know where to improve our strategy." }
        ]
    };

    const services = {
        eyebrow: "Empower Your Business with Our Services",
        title: "Our Proven Social Media Marketing Services",
        items: [
            {
                title: "Facebook Marketing",
                icon: <Target className="w-8 h-8" />,
                imgUrl: "https://images.unsplash.com/photo-1542744094-3a31f272c490?q=80&w=600&auto=format&fit=crop",
                paragraphs: [
                    "Through Facebook, you are certain to reach your target demographic since the social media platform has over 2 billion monthly active users. Use the most popular social media network to expand your company’s reach.",
                    "Facebook advertising services may help your company create an online following, raise brand recognition, and improve lead generation and revenue-generating initiatives. It’s a must-use advertising channel for organizations that want to develop because of Facebook’s large audience (it has more than two billion monthly users), extensive targeting possibilities, and a wide variety of ad kinds.",
                    "We at 21Twelve Interactive provide Facebook ad management services to get the most out of Facebook. We’re a one-stop solution for Facebook advertising, taking care of everything from developing your strategy and ad creatives to starting and tracking your campaigns."
                ],
                cta: "Hire us to get the best-in-class Facebook marketing services!"
            },
            {
                title: "Instagram Marketing",
                icon: <Component className="w-8 h-8" />,
                imgUrl: "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?q=80&w=600&auto=format&fit=crop",
                paragraphs: [
                    "Is Instagram advertising something you’re interested in using for your business? If this is the case, you need a strategy. Effective Instagram advertising needs strategic knowledge, a creative eye, and the time to execute and track results.",
                    "Many companies don’t have the means to run effective Instagram ads, so we’re here to assist. If you’re looking for an Instagram advertising agency, we’ll keep you up to speed on the most recent industry developments, algorithm adjustments, and best practices. The buyer’s journey may be broken down into phases, from awareness through conversion, and we can do so while keeping inside your budget.",
                    "Our agency can maximize your ad budget because of Instagram’s large and diversified user base, which includes more than 1 billion active monthly accounts and more than 500 million active daily accounts. We can target our digital advertising efforts to the specific individuals you want to reach by determining characteristics like geography, interests, demographics, habits, and more."
                ],
                cta: "Get Instagram marketing services quotes now!"
            },
            {
                title: "LinkedIn Marketing",
                icon: <Layout className="w-8 h-8" />,
                imgUrl: "https://images.unsplash.com/photo-1551650975-87deedd944c3?q=80&w=600&auto=format&fit=crop",
                paragraphs: [
                    "When it comes to targeting and efficiently reaching professionals all around the globe, LinkedIn stands out above the other social media giants that may claim comparable figures. Consider using LinkedIn advertising services if you’re planning to target individuals based on their professions, skill sets, industries, or professional interests since more than half of its members have a college degree.",
                    "Our LinkedIn advertising agency is always up to speed on algorithm updates and LinkedIn news to provide the greatest possible marketing results for your company. To get the best results for your company, we use our LinkedIn ad campaign management knowledge and smart selection among the platform’s many ad formatting and targeting options.",
                    "You can count on us to keep you updated throughout the process since we know how important it is to make the most of your financial resources. Every step of the way, you can be certain that we will use your resources effectively and productively to help you reach the goals you care about most."
                ],
                cta: "Give us a call right away to hire trusted LinkedIn marketing services!"
            },
            {
                title: "Twitter Marketing",
                icon: <Megaphone className="w-8 h-8" />,
                imgUrl: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=600&auto=format&fit=crop",
                paragraphs: [
                    "Get in touch with present and future customers quickly with Twitter advertising services. Become the company that people follow and believe in. The sheer volume of tweets on Twitter might be frightening, but we have the expertise to assist your company in cutting through the clutter and getting your message out there.",
                    "Does your company want to tap into the buying power of generations who have grown up in the digital age? We’ll use your marketing campaign’s latest industry information and platform technologies to target your targeted consumers. We follow industry best practices to get the greatest outcomes and make the most of every opportunity.",
                    "Don’t hesitate to contact us for your Twitter advertising management if you don’t have the time to build smart advertising campaigns, evaluate and make adjustments based on Twitter information, and keep up with industry developments."
                ],
                cta: "Hire us and get a cost-free Twitter marketing consultation now!"
            },
            {
                title: "eCommerce Social Media Services",
                icon: <ShoppingCart className="w-8 h-8" />,
                imgUrl: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?q=80&w=600&auto=format&fit=crop",
                paragraphs: [
                    "You can attract more clients to your eCommerce site and enhance your income through social network marketing. As a result, your eCommerce shop’s social media advertising campaigns may directly impact sales and profits.",
                    "Social media marketing strategies for eCommerce businesses include paid advertising on social media networks such as Facebook, Twitter, Instagram, LinkedIn, YouTube, and other platforms. Paid social media advertising allows you to expand the reach of your brand’s social media presence beyond what you can accomplish organically on social media.",
                    "Because of algorithm changes on social media networks such as Facebook, connecting consumers organically on these platforms is more difficult than ever. E-tailers should consider employing social media advertising to boost their online sales to grow their business."
                ],
                cta: "Connect with a reliable eCommerce social media services company today!"
            }
        ]
    };

    const industries = {
        eyebrow: "Custom IT Solutions for Varied Verticals",
        title: "Industries",
        description: "A perfect combination of ideation & innovation of digital products for all industry verticals. We help you streamline and improve customers’ engagement.",
        items: [
            { name: "eCommerce & Retail", desc: "Improve the brand presence and sales with an online marketplace", icon: <ShoppingCart /> },
            { name: "Health & Fitness", desc: "Perfect solutions for transformational health & fitness care", icon: <HeartPulse /> },
            { name: "Travel & Hospitality", desc: "Integrate your travel experience with robust digital platforms", icon: <Navigation /> },
            { name: "Education & e-Learning", desc: "Blending technology to bring seamless experience into education", icon: <GraduationCap /> },
            { name: "Fashion & Apparel", desc: "Robust fashion apps to improve your brand's presence", icon: <Shirt /> },
            { name: "Sports Industry", desc: "Creating modern websites and apps for the sports industry", icon: <Dumbbell /> },
            { name: "Legal Industry", desc: "New generation websites and apps for modern law firms", icon: <Scale /> },
            { name: "Blockchain & Crypto", desc: "Perfect apps for blockchain & crypto industry vertical", icon: <Bitcoin /> },
            { name: "Finance & Share Marketing", desc: "Trustworthy & next-gen mobile solutions for finance organizations", icon: <Landmark /> },
            { name: "Home Interior & Exterior", desc: "Rapidly develop a fully-functional home decor storefront", icon: <Paintbrush /> },
            { name: "Real-Estate Industry", desc: "Intelligent digital solutions for the real estate industry", icon: <Building /> },
            { name: "Hotel Industry", desc: "Smoothen your hotel processes with our digital solution", icon: <Building2 /> }
        ]
    };

    const reasons = {
        eyebrow: "Reason to Choose US",
        title: "Our Key Features",
        description: "When you work with 21Twelve Interactive, you’ll be able to see for yourself how our social media management efforts are boosting your online earnings.",
        items: [
            "Extensive onboarding process",
            "Customized marketing plan",
            "Managers who put customers first",
            "Extensive marketing experience",
            "Maximize the ROI",
            "Low-risk contracts",
            "Cost-efficient marketing strategies",
            "Accomplishing marketing objectives"
        ]
    };

    const contact = {
        title: "GET A FREE QUOTE",
        description: "We will get back to you within 24 hours"
    };

    return (
        <ModernServiceLayout
            seo={seoData}
            theme={theme}
            hero={hero}
            intro={intro}
            process={process}
            services={services}
            industries={industries}
            reasons={reasons}
            contact={contact}
        />
    );
};

export default SocialMedia;
